name: budgy

services:

  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/pgsql/data

volumes:
  
  database_data: